export const FETCH_NOMINATIM_START = 'FETCH_NOMINATIM_START'
export const FETCH_NOMINATIM_FINISH = 'FETCH_NOMINATIM_FINISH'
export const FETCH_NOMINATIM_ERROR = 'FETCH_NOMINATIM_ERROR'

export const CLEAR = 'CLEAR'

export const ACTIVE_ELEMENT = 'ACTIVE_ELEMENT'

export const SET_MAP = 'SET_MAP'