export const FETCH_NOMINATIM_INIT = 'FETCH_NOMINATIM_INIT'
export const FETCH_NOMINATIM_SUCCESS = 'FETCH_NOMINATIM_SUCCESS'

export const CLEAR = 'CLEAR'

export const ACTIVE_ELEMENT = 'ACTIVE_ELEMENT'
